In [4]:
import plotly.plotly as py
import plotly.graph_objs as go

import pandas as pd

#CONSTANTS declaration
__file__ = "./dat/province_code.xlsx"
PAGES_HREF = {'Khái quát': '/khai-quat', 'Theo môn': '/theo-mon', 'Theo tỉnh/thành': '/theo-tinh-thanh', 'Theo ban/khối': '/theo-ban-khoi', 'Theo khu vực/vùng miền': '/theo-vung-mien', 'Nơi thử nghiệm': '/thu-nghiem' }
BASE_DIR_DATA = "./dat/{}.csv"

#Other functions
def get_data(ref_province):
    data_wrapper = {}
    for province_id in range(64):
        try:
            data_wrapper[ref_province[ref_province["SỐ TT CỤM THI"] == province_id]["ĐIẠ PHƯƠNG"].values[0]] = pd.read_csv(BASE_DIR_DATA.format(province_id))
        except FileNotFoundError:
            pass
    return data_wrapper

"""
    Core variable for data in this app. This is the container of examination result of 62/63 provinces in Vietnam.
    province_ref : contains (id, geophraphical_name) E.g: (1, "TP.HCM")
    data_wraper  : dictionary of { id: DataFrame} which DataFrame contains examination result
"""
province_ref = pd.read_excel(__file__)
data_wrapper = get_data(province_ref)
test = pd.concat(data_wrapper.values()).reset_index().drop(columns=['index'])

In [4]:
test = pd.concat(data_wrapper.values()).reset_index().drop(columns=['index'])

In [45]:
test['KHỐI D'].mode()

0    14.2
dtype: object

In [5]:
test

,SBD,TOÁN,VĂN,LÝ,HÓA,SINH,SỬ,ĐỊA,GDCD,ANH,KHTN,KHXH,KHỐI A,KHỐI B,KHỐI C,KHỐI D,KHỐI A1
0,1063438,3.0,3.50,2.75,3.25,2.75,2.50,5.50,5.50,2.6,2.92,4.50,9.00,9.00,11.50,9.1,8.35
1,1063463,4.0,3.00,2.75,3.75,4.50,1.50,5.00,5.75,3.0,3.67,4.08,10.50,12.25,9.50,10,9.75
2,1063464,5.0,3.00,3.75,2.25,3.50,3.50,5.75,5.75,3.0,3.17,5.00,11.00,10.75,12.25,11,11.75
3,1063470,2.6,4.50,2.00,3.50,3.25,1.75,4.25,6.25,3.0,2.92,4.08,8.10,9.35,10.50,10.1,7.60
4,1063477,3.2,5.00,2.00,3.00,3.00,2.50,4.00,7.00,3.4,2.67,4.50,8.20,9.20,11.50,11.6,8.60
5,1062974,6.6,6.50,NaN,NaN,NaN,4.25,5.25,7.00,5.0,NaN,5.50,NaN,NaN,16.00,18.1,NaN
6,1063007,2.4,2.75,NaN,NaN,NaN,2.25,3.50,4.50,2.8,NaN,3.42,NaN,NaN,8.50,7.95,NaN
7,1063017,4.4,6.00,NaN,NaN,NaN,3.25,5.25,7.50,3.2,NaN,5.33,NaN,NaN,14.50,13.6,NaN
8,1063020,4.2,3.50,NaN,NaN,NaN,2.50,4.00,4.50,2.2,NaN,3.67,NaN,NaN,10.00,9.9,NaN
9,1062989,3.4,6.25,NaN,NaN,NaN,5.50,8.50,7.50,2.8,NaN,7.17,NaN,NaN,20.25,12.45,NaN
10,1062995,4.0,3.00,NaN,NaN,NaN,4.00,4.25,6.50,3.2,NaN,4.92,NaN,NaN,11.25,10.2,NaN
11,1062999,2.8,2.25,NaN,NaN,NaN,2.75,4.75,4.50,2.4,NaN,4.00,NaN,NaN,9.75,7.45,NaN
12,1063022,3.6,4.50,NaN,NaN,NaN,2.50,4.75,6.50,1.6,NaN,4.58,NaN,NaN,11.75,9.7,NaN
13,1063026,6.6,7.00,NaN,NaN,NaN,3.75,6.00,7.25,7.0,NaN,5.67,NaN,NaN,16.75,20.6,NaN
14,1062990,4.0,4.75,NaN,NaN,NaN,4.75,5.75,6.75,2.8,NaN,5.75,NaN,NaN,15.25,11.55,NaN
15,1063008,6.8,8.00,NaN,NaN,NaN,2.75,5.75,6.25,5.6,NaN,4.92,NaN,NaN,16.50,20.4,NaN
16,1062482,4.4,8.25,5.25,6.75,4.25,NaN,NaN,NaN,2.4,5.42,NaN,16.40,15.40,NaN,15.05,12.05
17,1062485,6.8,7.50,3.75,4.50,4.00,NaN,NaN,NaN,5.2,4.08,NaN,15.05,15.30,NaN,19.5,15.75
18,1062487,5.8,7.25,4.50,5.25,6.75,NaN,NaN,NaN,3.4,5.50,NaN,15.55,17.80,NaN,16.45,13.70
19,1062492,5.4,4.00,4.25,4.50,3.00,NaN,NaN,NaN,2.2,3.92,NaN,14.15,12.90,NaN,11.6,11.85
20,1062494,7.2,5.25,5.75,3.00,4.00,NaN,NaN,NaN,8.0,4.25,NaN,15.95,14.20,NaN,20.45,20.95
21,1062497,7.2,7.50,7.50,6.00,5.25,NaN,NaN,NaN,4.6,6.25,NaN,20.70,18.45,NaN,19.3,19.30
22,1062502,6.0,4.00,5.75,4.50,2.50,NaN,NaN,NaN,4.0,4.25,NaN,16.25,13.00,NaN,14,15.75
23,1062504,6.8,6.50,5.75,4.50,4.50,NaN,NaN,NaN,2.2,4.92,NaN,17.05,15.80,NaN,15.5,14.75
24,1062510,6.8,6.75,5.00,3.00,3.25,NaN,NaN,NaN,4.6,3.75,NaN,14.80,13.05,NaN,18.15,16.40
25,1062511,6.4,3.00,5.00,4.75,3.75,NaN,NaN,NaN,2.8,4.50,NaN,16.15,14.90,NaN,12.2,14.20
26,1062517,6.2,7.00,4.25,3.50,3.50,NaN,NaN,NaN,2.8,3.75,NaN,13.95,13.20,NaN,16,13.25
27,1062522,6.8,7.00,3.50,4.25,5.00,NaN,NaN,NaN,8.0,4.25,NaN,14.55,16.05,NaN,21.8,18.30
28,1062529,2.4,3.75,3.00,2.00,3.00,NaN,NaN,NaN,2.4,2.67,NaN,7.40,7.40,NaN,8.55,7.80
29,1062540,5.6,3.75,2.75,5.00,4.75,NaN,NaN,NaN,3.4,4.17,NaN,13.35,15.35,NaN,12.75,11.75
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
827733,61006796,3.8,4.00,2.25,3.00,4.75,NaN,NaN,NaN,2.2,3.33,NaN,9.05,11.55,NaN,10,8.25
827734,61006689,4.4,4.50,3.75,4.25,4.50,NaN,NaN,NaN,3.4,4.17,NaN,12.40,13.15,NaN,12.3,11.55
827735,61004575,4.2,7.50,NaN,NaN,NaN,4.25,5.50,8.00,3.6,NaN,5.92,NaN,NaN,17.25,15.3,NaN
827736,61004585,3.8,6.50,NaN,NaN,NaN,3.75,7.00,8.25,4.2,NaN,6.33,NaN,NaN,17.25,14.5,NaN
827737,61004795,2.8,5.50,NaN,NaN,NaN,4.25,5.25,5.50,2.4,NaN,5.00,NaN,NaN,15.00,10.7,NaN
827738,61004825,4.2,6.50,NaN,NaN,NaN,4.25,6.25,6.25,3.6,NaN,5.58,NaN,NaN,17.00,14.3,NaN
827739,61004858,4.4,6.00,NaN,NaN,NaN,3.00,5.25,8.00,2.6,NaN,5.42,NaN,NaN,14.25,13,NaN
827740,61004952,4.8,7.50,NaN,NaN,NaN,2.75,6.00,7.00,3.6,NaN,5.25,NaN,NaN,16.25,15.9,NaN
827741,61005093,3.4,7.50,NaN,NaN,NaN,6.25,6.00,6.75,3.8,NaN,6.33,NaN,NaN,19.75,14.7,NaN
827742,61005585,3.6,5.50,NaN,NaN,NaN,3.25,3.25,6.50,2.2,NaN,4.33,NaN,NaN,12.00,11.3,NaN
827743,61005825,2.4,3.50,NaN,NaN,NaN,3.75,4.25,6.25,2.0,NaN,4.75,NaN,NaN,11.50,7.9,NaN
827744,61005840,4.0,7.00,NaN,NaN,NaN,3.25,8.00,8.50,3.4,NaN,6.58,NaN,NaN,18.25,14.4,NaN
827745,61008179,5.0,4.50,6.50,3.75,3.50,NaN,NaN,NaN,4.0,4.58,NaN,15.25,12.25,NaN,13.5,15.50
827746,61004151,3.4,5.75,NaN,NaN,NaN,4.00,4.50,7.25,3.4,NaN,5.25,NaN,NaN,14.25,12.55,NaN
827747,61004384,4.2,5.00,NaN,NaN,NaN,2.50,5.00,7.75,3.4,NaN,5.08,NaN,NaN,12.50,12.6,NaN
827748,61004408,3.0,7.75,NaN,NaN,NaN,5.00,6.50,7.00,3.6,NaN,6.17,NaN,NaN,19.25,14.35,NaN
827749,61004024,4.6,7.00,NaN,NaN,NaN,4.00,6.75,7.75,2.8,NaN,6.17,NaN,NaN,17.75,14.4,NaN
827750,61004204,5.2,7.00,NaN,NaN,NaN,6.25,8.75,9.25,5.4,NaN,8.08,NaN,NaN,22.00,17.6,NaN
827751,61004237,4.6,3.50,NaN,NaN,NaN,2.50,5.25,6.00,3.0,NaN,4.58,NaN,NaN,11.25,11.1,NaN
827752,61004301,3.8,5.25,NaN,NaN,NaN,4.00,5.25,8.50,2.4,NaN,5.92,NaN,NaN,14.50,11.45,NaN
827753,61004643,3.6,5.25,NaN,NaN,NaN,4.50,5.00,7.25,2.4,NaN,5.58,NaN,NaN,14.75,11.25,NaN
827754,61004683,4.6,6.00,NaN,NaN,NaN,3.50,4.50,7.25,3.8,NaN,5.08,NaN,NaN,14.00,14.4,NaN
827755,61004459,3.0,3.75,NaN,NaN,NaN,2.25,6.75,6.50,3.0,NaN,5.17,NaN,NaN,12.75,9.75,NaN
827756,61004474,3.6,5.00,NaN,NaN,NaN,3.25,5.25,6.50,4.0,NaN,5.00,NaN,NaN,13.50,12.6,NaN
827757,61002646,3.8,3.25,NaN,NaN,NaN,2.75,8.25,8.25,3.8,NaN,6.42,NaN,NaN,14.25,10.85,NaN
827758,61002654,5.6,6.25,3.00,5.75,3.25,NaN,NaN,NaN,3.2,4.00,NaN,14.35,14.60,NaN,15.05,11.80
827759,61003116,6.6,5.50,5.25,5.75,6.00,NaN,NaN,NaN,4.4,5.67,NaN,17.60,18.35,NaN,16.5,16.25
827760,61003743,6.2,7.25,4.75,6.50,5.25,NaN,NaN,NaN,5.4,5.50,NaN,17.45,17.95,NaN,18.85,16.35
827761,61003786,5.8,8.75,NaN,NaN,NaN,4.50,7.50,8.50,4.6,NaN,6.83,NaN,NaN,20.75,19.15,NaN
827762,61003862,5.8,7.75,7.25,5.00,5.75,NaN,NaN,NaN,3.6,6.00,NaN,18.05,16.55,NaN,17.15,16.65

In [32]:
test[test['SBD'] ==  106347].values.shape[0] == 0

True

In [8]:
test.describe()

,SBD,TOÁN,VĂN,LÝ,HÓA,SINH,SỬ,ĐỊA,GDCD,ANH,KHTN,KHXH,KHỐI A,KHỐI B,KHỐI C,KHỐI A1
count,8.277630e+05,823976.000000,809844.000000,354554.000000,358449.000000,350220.000000,503742.000000,489044.000000,426381.000000,730909.000000,345462.000000,420853.000000,352192.000000,350120.000000,488393.000000,336928.000000
mean,2.878327e+07,4.869181,5.419870,4.951471,4.851609,4.538225,3.789503,5.467460,7.131536,3.924110,4.778271,5.501910,15.499799,15.088082,14.567428,15.018494
std,1.934710e+07,1.453694,1.465532,1.549535,1.539051,1.247654,1.240106,1.261482,1.234873,1.577087,1.096763,1.004653,3.680329,3.237084,3.253977,3.492587
min,1.000019e+06,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1.200172e+07,3.800000,4.500000,3.750000,3.750000,3.750000,3.000000,4.750000,6.500000,2.800000,4.000000,4.830000,13.050000,12.950000,12.250000,12.650000
50%,3.001086e+07,5.000000,5.500000,5.000000,4.750000,4.500000,3.500000,5.500000,7.250000,3.600000,4.750000,5.500000,15.600000,15.100000,14.500000,14.900000
75%,4.500150e+07,6.000000,6.500000,6.000000,6.000000,5.250000,4.500000,6.250000,8.000000,4.600000,5.580000,6.170000,18.000000,17.200000,16.750000,17.300000
max,6.400622e+07,10.000000,9.750000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,9.330000,9.580000,29.050000,29.550000,28.500000,28.950000

In [11]:
test.describe()['SBD']['count']

827763.0

In [17]:
test.describe().loc['mean', :]['TOÁN']

4.869180655747113

In [19]:
test.describe().loc['mean', :].keys()

Index(['SBD', 'TOÁN', 'VĂN', 'LÝ', 'HÓA', 'SINH', 'SỬ', 'ĐỊA', 'GDCD', 'ANH',
       'KHTN', 'KHXH', 'KHỐI A', 'KHỐI B', 'KHỐI C', 'KHỐI A1'],
      dtype='object')

In [20]:
test.describe().loc['mean', :].keys()

Index(['SBD', 'TOÁN', 'VĂN', 'LÝ', 'HÓA', 'SINH', 'SỬ', 'ĐỊA', 'GDCD', 'ANH',
       'KHTN', 'KHXH', 'KHỐI A', 'KHỐI B', 'KHỐI C', 'KHỐI A1'],
      dtype='object')

In [36]:
test.describe().iloc[1].values

array([2.87832745e+07, 4.86918066e+00, 5.41986993e+00, 4.95147072e+00,
       4.85160946e+00, 4.53822526e+00, 3.78950336e+00, 5.46746049e+00,
       7.13153553e+00, 3.92411011e+00, 4.77827124e+00, 5.50191041e+00,
       1.54997993e+01, 1.50880824e+01, 1.45674282e+01, 1.50184936e+01])

In [23]:
test.describe().columns.values

array(['SBD', 'TOÁN', 'VĂN', 'LÝ', 'HÓA', 'SINH', 'SỬ', 'ĐỊA', 'GDCD',
       'ANH', 'KHTN', 'KHXH', 'KHỐI A', 'KHỐI B', 'KHỐI C', 'KHỐI A1'],
      dtype=object)

In [57]:
desc = test.describe().round(2)

In [58]:
desc

,SBD,TOÁN,VĂN,LÝ,HÓA,SINH,SỬ,ĐỊA,GDCD,ANH,KHTN,KHXH,KHỐI A,KHỐI B,KHỐI C,KHỐI A1
count,827763.00,823976.00,809844.00,354554.00,358449.00,350220.00,503742.00,489044.00,426381.00,730909.00,345462.00,420853.00,352192.00,350120.00,488393.00,336928.00
mean,28783274.51,4.87,5.42,4.95,4.85,4.54,3.79,5.47,7.13,3.92,4.78,5.50,15.50,15.09,14.57,15.02
std,19347095.61,1.45,1.47,1.55,1.54,1.25,1.24,1.26,1.23,1.58,1.10,1.00,3.68,3.24,3.25,3.49
min,1000019.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
25%,12001724.50,3.80,4.50,3.75,3.75,3.75,3.00,4.75,6.50,2.80,4.00,4.83,13.05,12.95,12.25,12.65
50%,30010856.00,5.00,5.50,5.00,4.75,4.50,3.50,5.50,7.25,3.60,4.75,5.50,15.60,15.10,14.50,14.90
75%,45001499.50,6.00,6.50,6.00,6.00,5.25,4.50,6.25,8.00,4.60,5.58,6.17,18.00,17.20,16.75,17.30
max,64006216.00,10.00,9.75,10.00,10.00,10.00,10.00,10.00,10.00,10.00,9.33,9.58,29.05,29.55,28.50,28.95

In [59]:
for index, row in desc.iterrows(): 
    print(index)

for index, row in desc.iterrows(): 
    print(row.name)

count
mean
std
min
25%
50%
75%
max
count
mean
std
min
25%
50%
75%
max

In [43]:
desc[['TOÁN', 'VĂN', 'LÝ', 'HÓA', 'SINH', 'SỬ', 'ĐỊA', 'GDCD', 'ANH',
       'KHTN', 'KHXH']]

,TOÁN,VĂN,LÝ,HÓA,SINH,SỬ,ĐỊA,GDCD,ANH,KHTN,KHXH
count,823976.000000,809844.000000,354554.000000,358449.000000,350220.000000,503742.000000,489044.000000,426381.000000,730909.000000,345462.000000,420853.000000
mean,4.869181,5.419870,4.951471,4.851609,4.538225,3.789503,5.467460,7.131536,3.924110,4.778271,5.501910
std,1.453694,1.465532,1.549535,1.539051,1.247654,1.240106,1.261482,1.234873,1.577087,1.096763,1.004653
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,3.800000,4.500000,3.750000,3.750000,3.750000,3.000000,4.750000,6.500000,2.800000,4.000000,4.830000
50%,5.000000,5.500000,5.000000,4.750000,4.500000,3.500000,5.500000,7.250000,3.600000,4.750000,5.500000
75%,6.000000,6.500000,6.000000,6.000000,5.250000,4.500000,6.250000,8.000000,4.600000,5.580000,6.170000
max,10.000000,9.750000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,9.330000,9.580000

In [60]:
desc['KHỐI C']

count    488393.00
mean         14.57
std           3.25
min           0.00
25%          12.25
50%          14.50
75%          16.75
max          28.50
Name: KHỐI C, dtype: float64

In [33]:
PAGES_HREF = {'Khái quát': '/khai-quat', 'Theo môn': '/theo-mon', 'Theo tỉnh/thành': '/theo-tinh-thanh', 'Theo ban/khối': '/theo-ban-khoi', 'Theo khu vực/vùng miền': '/theo-vung-mien', 'Nơi thử nghiệm': '/thu-nghiem' }

In [34]:
landing_page = "Theo môn"
subtab = ['table', 'graph']
for tab in subtab:
    print("{}-{}".format(PAGES_HREF[landing_page].replace('/', '#'),tab))

#theo-mon-table
#theo-mon-graph

In [10]:
SUBJECTS = ['TOÁN', 'VĂN', 'LÝ', 'HÓA', 'SINH', 'SỬ', 'ĐỊA', 'GDCD', 'ANH']
x_data = SUBJECTS

y_data = []
for subject in SUBJECTS:
    y_data.append(test[subject])

colors = ['rgba(93, 164, 214, 0.5)', 'rgba(255, 144, 14, 0.5)', 'rgba(44, 160, 101, 0.5)', 'rgba(255, 65, 54, 0.5)', 'rgba(207, 114, 255, 0.5)', 'rgba(127, 96, 0, 0.5)', 'rgba(255, 224, 156, 0.5)', 'khaki', 'lightsalmon']

traces = []

for xd, yd, cls in zip(x_data, y_data, colors):
        traces.append(go.Box(
            y=yd,
            name=xd,
            boxpoints=False,
            jitter=0.5,
            whiskerwidth=0.2,
            fillcolor=cls,
            marker=dict(
                size=2,
            ),
            line=dict(width=1),
        ))

layout = go.Layout(
    title='Points Scored by the Top 9 Scoring NBA Players in 2012',
    yaxis=dict(
        autorange=True,
        showgrid=True,
        zeroline=True,
        dtick=5,
        gridcolor='rgb(255, 255, 255)',
        gridwidth=1,
        zerolinecolor='rgb(255, 255, 255)',
        zerolinewidth=2,
    ),
    margin=dict(
        l=40,
        r=30,
        b=80,
        t=100,
    ),
    paper_bgcolor='rgb(243, 243, 243)',
    plot_bgcolor='rgb(243, 243, 243)',
    showlegend=False
)

fig = go.Figure(data=traces, layout=layout)
py.iplot(fig, filename = "Box Plot Styling Outliers")

E:\ProgramData\Anaconda3\lib\site-packages\plotly\plotly\plotly.py:233: UserWarning:

Woah there! Look at all those points! Due to browser limitations, the Plotly SVG drawing functions have a hard time graphing more than 500k data points for line charts, or 40k points for other types of charts. Here are some suggestions:
(1) Use the `plotly.graph_objs.Scattergl` trace object to generate a WebGl graph.
(2) Trying using the image API to return an image instead of a graph URL
(3) Use matplotlib
(4) See if you can create your visualization with fewer data points

If the visualization you're using aggregates points (e.g., box plot, histogram, etc.) you can disregard this warning.

PlotlyRequestError:
<html><head>
<meta http-equiv="content-type" content="text/html;charset=utf-8">
<title>502 Server Error</title>
</head>
<body text=#000000 bgcolor=#ffffff>
<h1>Error: Server Error</h1>
<h2>The server encountered a temporary error and could not complete your request.<p>Please try again in 30 seconds.</h2>
<h2></h2>
</body></html>